# Use the official Node.js image
FROM node:18-alpine

#Set the working directory
WORKDIR /usr/src/app

# Copy package.json and isntall dependencies
COPY package.json package-lock.json ./
RUN npm install --production

# Copy the rest of the application code
COPY . .
COPY .env.local .env.local


# Build the Next.js app
RUN npm run build

# Expose port 3000 
EXPOSE 3000 80

# Start the app
CMD ["npm", "start"]

